name: Functions
author: Ad5001
version: "1.2.1"
api:
- 3.0.0-ALPHA8
main: Ad5001\Functions\Main
commands: 
    function:
        description: "Create, manage and remove functions with this command"
        usage: "/function <sub-command> <function> parameters..."
        permission: func.command.function
permissions:
    func.command.function:
        default: op
        description: "Create, manage and remove functions with this command"
    func.use.default:
        default: true
        description: "Defines users permission to use a specific function if permission node func.use.functionname is not set"
